################################
## JWT Signing Certificate Secret
#################################
{{- if not .Values.platform.singleNamespace }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.webserver.jwtSigningCertificateSecretName }}
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    replicator.v1.mittwald.de/replicate-from: {{ template "replicator.replicateFrom" . }}
type: Opaque
data: {}
{{- end }}
