################################
## Astronomer Prisma Secret
#################################
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-prisma-api-secret
  labels:
    component: prisma
    tier: astronomer
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
type: Opaque
data:
  api-secret: {{ randAlphaNum 40 | b64enc | quote }}
  service-secret: {{ randAlphaNum 40 | b64enc | quote }}
