name: astronomer-platform
version: 0.10.3-astro.7
appVersion: 0.10.3
description: Helm chart to deploy the Astronomer Platform
icon: https://www.astronomer.io/static/iconforLIGHTbackground.svg
keywords:
  - astronomer
