################################
## Houston JWT Certificate Secret
#################################
{{- $ca := genCA "ca" 3650 }}
{{- $cn := printf "%s-houston" .Release.Name -}}
{{- $altName1 := printf "%s.%s" $cn .Release.Namespace }}
{{- $altName2 := printf "%s.%s.svc" $cn .Release.Namespace }}
{{- $cert := genSignedCert $cn nil (list $altName1 $altName2) 3650 $ca }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "houston.jwtCertificateSecret" . }}
  labels:
    component: houston
    tier: astronomer
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
  annotations:
    # Signal to replicator that this secret needs to be synced to any namespace
    # that matches the allowed-namespaces regex.
    "replicator.v1.mittwald.de/replication-allowed": "true"
    "replicator.v1.mittwald.de/replication-allowed-namespaces": {{ printf "%s-*" .Release.Namespace }}
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
type: Opaque
data:
  tls.crt: {{ b64enc $cert.Cert }}
  tls.key: {{ b64enc $cert.Key }}
