################################
## Houston Cleanup CronJob
#################################
{{- if .Values.houston.cleanup.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-cleanup
  labels:
    tier: astronomer
    component: houston
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: {{ .Values.houston.cleanup.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: cleanup
              image: {{ template "houston.image" . }}
              imagePullPolicy: {{ .Values.images.houston.pullPolicy }}
              command: ["npm", "run", "deployment-cleanup", "--older-than={{ .Values.houston.cleanup.olderThan }}"]
              volumeMounts:
                {{- include "houston_volume_mounts" . | indent 16 }}
              env:
                {{- include "houston_environment" . | indent 16 }}
          volumes:
            {{- include "houston_volumes" . | indent 12 }}
{{- end }}
