################################
## Houston Bootstrap Role
#################################
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ template "houston.updaterServiceAccount" . }}
  labels:
    tier: houston
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}