################################
## Prometheus NetworkPolicy
#################################
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "prometheus.fullname" . }}-policy
  labels:
    tier: monitoring
    component: {{ template "prometheus.name" . }}
    chart: {{ template "prometheus.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      tier: monitoring
      component: {{ template "prometheus.name" . }}
      release: {{ .Release.Name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          tier: astronomer
          component: houston
          release: {{ .Release.Name }}
    - podSelector:
        matchLabels:
          tier: monitoring
          component: grafana
          release: {{ .Release.Name }}
    ports:
    - protocol: TCP
      port: {{ .Values.ports.http }}
