################################
## Kube Replicator Deployment
#################################
{{- if not .Values.global.singleNamespace }}
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: {{ .Release.Name }}-kube-replicator
  labels:
    component: kube-replicator
    tier: astronomer
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: astronomer
      component: kube-replicator
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        tier: astronomer
        component: kube-replicator
        release: {{ .Release.Name }}
    spec:
      restartPolicy: Always
      serviceAccountName: {{ template "kubeReplicator.serviceAccount" . }}
      containers:
        - name: {{ .Release.Name }}-kube-replicator
          image: {{ template "kubeReplicator.image" . }}
          imagePullPolicy: {{ .Values.images.houston.pullPolicy }}
          resources:
{{ toYaml .Values.kubeReplicator.resources | indent 12 }}
{{- end }}
