################################
## Kube Replicator NetworkPolicy
#################################
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-kube-replicator-policy
  labels:
    tier: airflow
    component: kube-replicator-policy
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      tier: astronomer
      component: kube-replicator
      release: {{ .Release.Name }}
  policyTypes:
  - Ingress
