# Default values for Grafana.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nodeSelector: {}
affinity: {}
tolerations: []

images:
  grafana:
    repository: astronomerinc/ap-grafana
    tag: 0.9.3-alpha.2
    pullPolicy: IfNotPresent
  dbBootstrapper:
    repository: astronomerinc/ap-db-bootstrapper
    tag: 0.9.3-alpha.2
    pullPolicy: IfNotPresent

backendSecretName: ~
backendConnection: {}
  # user: ~
  # pass: ~
  # host: ~
  # port: ~
  # db: ~

ports:
  http: 3000

resources: {}
#  limits:
#   cpu: 100m
#   memory: 128Mi
#  requests:
#   cpu: 100m
#   memory: 128Mi