################################
## Curator CronJob
#################################
{{- if .Values.curator.enabled }}
apiVersion: {{ template "curator.cronJob.apiVersion" . }}
kind: CronJob
metadata:
  name: {{ template "elasticsearch.fullname" . }}-curator
  annotations:
    # https://github.com/istio/istio/issues/6324
    # TODO: turn back on after upgrading to istio 1.3
    # and implementing call to pilot-agent's /quitquitquit
    sidecar.istio.io/inject: "false"
  labels:
    tier: logging
    component: {{ template "elasticsearch.name" . }}
    chart: {{ template "elasticsearch.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: {{ .Values.curator.schedule }}
  jobTemplate:
    spec:
      template:
{{- if or .Values.common.podAnnotations .Values.curator.podAnnotations }}
        metadata:
          annotations:
{{- end }}
{{- if .Values.common.podAnnotations }}
{{ toYaml .Values.common.podAnnotations | indent 12 }}
{{- end }}
{{- if .Values.curator.podAnnotations }}
{{ toYaml .Values.curator.podAnnotations | indent 12 }}
{{- end }}
        spec:
          containers:
          - name: curator
            image: {{ template "curator.image" . }}
            imagePullPolicy: {{ .Values.images.curator.pullPolicy }}
            command: ["/bin/sh", "-c"]
            args: ["/usr/bin/curator --config /etc/config/config.yml /etc/config/action_file.yml; exit_code=$?; wget --post-data='not=used' http://127.0.0.1:15020/quitquitquit; exit $exit_code;"]
            volumeMounts:
              - name: config-volume
                mountPath: /etc/config
          volumes:
            - name: config-volume
              configMap:
                name: {{ template "elasticsearch.fullname" . }}-curator-config
          restartPolicy: OnFailure
{{- end }}
