################################
## KubeD ServiceAccount
#################################
{{- if .Values.global.rbacEnabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kubed.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    tier: kubed
    component: {{ template "kubed.name" . }}
    chart: {{ template "kubed.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{ end }}
