################################
## KubeD Service
#################################
apiVersion: v1
kind: Service
metadata:
  name: {{ template "kubed.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    tier: {{ template "kubed.name" . }}
    component: {{ template "kubed.name" . }}
    chart: {{ template "kubed.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  # Port used to expose admission webhook apiserver
  - name: api
    port: 443
    targetPort: 8443
  selector:
    tier: {{ template "kubed.name" . }}
    component: {{ template "kubed.name" . }}
    release: {{ .Release.Name }}
