################################
## KubeD ClusterRole
#################################
{{- if .Values.global.rbacEnabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "kubed.fullname" . }}
  labels:
    tier: {{ template "kubed.name" . }}
    component: {{ template "kubed.name" . }}
    chart: {{ template "kubed.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  - secrets
  verbs: ["get", "create", "patch", "delete"]
- apiGroups:
    - ""
  resources:
    - namespaces
  verbs: ["get"]
{{ end }}
